/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { HouseService } from "../house.service";
import { HouseCreateInput } from "./HouseCreateInput";
import { House } from "./House";
import { HouseFindManyArgs } from "./HouseFindManyArgs";
import { HouseWhereUniqueInput } from "./HouseWhereUniqueInput";
import { HouseUpdateInput } from "./HouseUpdateInput";
import { BookingFindManyArgs } from "../../booking/base/BookingFindManyArgs";
import { Booking } from "../../booking/base/Booking";
import { BookingWhereUniqueInput } from "../../booking/base/BookingWhereUniqueInput";
import { RoomFindManyArgs } from "../../room/base/RoomFindManyArgs";
import { Room } from "../../room/base/Room";
import { RoomWhereUniqueInput } from "../../room/base/RoomWhereUniqueInput";

export class HouseControllerBase {
  constructor(protected readonly service: HouseService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: House })
  async createHouse(@common.Body() data: HouseCreateInput): Promise<House> {
    return await this.service.createHouse({
      data: data,
      select: {
        address: true,
        createdAt: true,
        id: true,
        price: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [House] })
  @ApiNestedQuery(HouseFindManyArgs)
  async houses(@common.Req() request: Request): Promise<House[]> {
    const args = plainToClass(HouseFindManyArgs, request.query);
    return this.service.houses({
      ...args,
      select: {
        address: true,
        createdAt: true,
        id: true,
        price: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: House })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async house(
    @common.Param() params: HouseWhereUniqueInput
  ): Promise<House | null> {
    const result = await this.service.house({
      where: params,
      select: {
        address: true,
        createdAt: true,
        id: true,
        price: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: House })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateHouse(
    @common.Param() params: HouseWhereUniqueInput,
    @common.Body() data: HouseUpdateInput
  ): Promise<House | null> {
    try {
      return await this.service.updateHouse({
        where: params,
        data: data,
        select: {
          address: true,
          createdAt: true,
          id: true,
          price: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: House })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteHouse(
    @common.Param() params: HouseWhereUniqueInput
  ): Promise<House | null> {
    try {
      return await this.service.deleteHouse({
        where: params,
        select: {
          address: true,
          createdAt: true,
          id: true,
          price: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/bookings")
  @ApiNestedQuery(BookingFindManyArgs)
  async findBookings(
    @common.Req() request: Request,
    @common.Param() params: HouseWhereUniqueInput
  ): Promise<Booking[]> {
    const query = plainToClass(BookingFindManyArgs, request.query);
    const results = await this.service.findBookings(params.id, {
      ...query,
      select: {
        createdAt: true,
        customerName: true,
        endDate: true,

        house: {
          select: {
            id: true,
          },
        },

        id: true,
        startDate: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/bookings")
  async connectBookings(
    @common.Param() params: HouseWhereUniqueInput,
    @common.Body() body: BookingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      bookings: {
        connect: body,
      },
    };
    await this.service.updateHouse({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/bookings")
  async updateBookings(
    @common.Param() params: HouseWhereUniqueInput,
    @common.Body() body: BookingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      bookings: {
        set: body,
      },
    };
    await this.service.updateHouse({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/bookings")
  async disconnectBookings(
    @common.Param() params: HouseWhereUniqueInput,
    @common.Body() body: BookingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      bookings: {
        disconnect: body,
      },
    };
    await this.service.updateHouse({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/rooms")
  @ApiNestedQuery(RoomFindManyArgs)
  async findRooms(
    @common.Req() request: Request,
    @common.Param() params: HouseWhereUniqueInput
  ): Promise<Room[]> {
    const query = plainToClass(RoomFindManyArgs, request.query);
    const results = await this.service.findRooms(params.id, {
      ...query,
      select: {
        createdAt: true,

        house: {
          select: {
            id: true,
          },
        },

        id: true,
        name: true,
        size: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/rooms")
  async connectRooms(
    @common.Param() params: HouseWhereUniqueInput,
    @common.Body() body: RoomWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      rooms: {
        connect: body,
      },
    };
    await this.service.updateHouse({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/rooms")
  async updateRooms(
    @common.Param() params: HouseWhereUniqueInput,
    @common.Body() body: RoomWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      rooms: {
        set: body,
      },
    };
    await this.service.updateHouse({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/rooms")
  async disconnectRooms(
    @common.Param() params: HouseWhereUniqueInput,
    @common.Body() body: RoomWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      rooms: {
        disconnect: body,
      },
    };
    await this.service.updateHouse({
      where: params,
      data,
      select: { id: true },
    });
  }
}
